version: '3.9'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - "MONGODB_URL=${MONGODB_URL}"
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
