version: '3.9'

services:
  postgres:
    image: postgres:13
    restart: always
    hostname: postgres
    container_name: postgres
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  postgres:


